[project]
name = "check-english-analyze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "g2p-en>=2.1.0",
    "phonemizer>=3.3.0",
    "ruff>=0.11.6",
]
