name: スナップショット更新
description: プロジェクトの依存関係をセットアップしてpytestスナップショットを更新する

inputs:
  commit-message:
    description: コミットメッセージ
    required: true
    default: "test: スナップショット更新"

outputs:
  has-changes:
    description: 変更があったかどうか
    value: ${{ steps.check-changes.outputs.has_changes }}

runs:
  using: composite
  steps:
    - name: <Setup> Python環境セットアップ
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: <Setup> uvのインストール
      uses: astral-sh/setup-uv@v3

    - name: <Build> 依存関係のインストール
      run: uv sync --dev
      shell: bash

    - name: <Build> システム依存関係のインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y festival festvox-us-slt-hts espeak-ng
      shell: bash

    - name: <Build> Miniconda & MFAのインストール
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source $HOME/miniconda/bin/activate
        # NOTE: joblib<1.4 to avoid MFA error
        conda create -y -n mfa -c conda-forge montreal-forced-aligner "joblib<1.4"
      shell: bash

    - name: <Build> NLTKリソースのダウンロード
      run: uv run python -c "import nltk; nltk.download('averaged_perceptron_tagger_eng', quiet=True)"
      shell: bash

    - name: <Deploy> スナップショット更新
      run: PYTHONPATH=. uv run pytest -sv --snapshot-update
      shell: bash

    - name: <Deploy> 変更確認
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: <Deploy> 変更をコミット・プッシュ
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "${{ inputs.commit-message }}

        🤖 Generated with GitHub Actions

        Co-Authored-By: GitHub Action <action@github.com>"
        git push
      shell: bash
