name: test

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: <Setup> リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: <Setup> uvのインストール
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: <Setup> 依存関係のインストール
        run: uv sync --locked --all-extras --dev

      - name: <Setup> festival, espeakのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y festival festvox-us-slt-hts espeak

      - name: <Setup> Miniconda & MFAのインストール
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          source $HOME/miniconda/bin/activate
          conda create -y -n mfa -c conda-forge montreal-forced-aligner

      - name: <Setup> G2P_en NLTKリソースのダウンロード
        run: uv run python -c "import nltk; nltk.download('averaged_perceptron_tagger_eng', quiet=True)"

      - name: <Test> リントチェック
        run: uv run ruff check

      - name: <Test> フォーマットチェック
        run: uv run ruff format --check

      - name: <Test> テスト実行
        run: PYTHONPATH=. uv run pytest -sv
